### ISSUE TITLE
Won't install in node 19

### ISSUE THREAD

**Issue by Fmstrat** [valeriangalliat/node-firefox-sync#2]
From `npm i --save firefox-sync`:

```
1 info using npm@8.19.3                                     
2 info using node@v19.2.0   
...
101 verbose stack Error: An unknown git error occurred
101 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/@npmcli/git/lib/make-error.js:28:13)
101 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/git/lib/spawn.js:37:26
101 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

This was using the latest `node:alpine` docker container.

**Comment by Fmstrat** [comment]
Guessing it has to do with this: https://www.npmjs.com/package/fxa-js-client

Any potential workarounds?
